<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FMHTC77" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.175" errors="0" timestamp="2022-09-13T13:39:31 IST">
  <testcase classname="retryLogic.MyTests" name="Test1" time="0.031">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogic.MyTests" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogic.MyTests" name="Test1" time="0.004">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogic.MyTests" name="Test1" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.MyTests.Test1(MyTests.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogic.MyTests" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogic.MyTests" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogic.MyTests" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogic.MyTests" name="Test2" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.MyTests.Test2(MyTests.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogic.MyTests" name="Test3" time="0.006"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
